VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet3"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

'商品编码 1
'商品名称 2
'规格 3
'单位 4
'分类 5
'操作时间 6
'操作类型 7
'操作前库存 8
'操作数量 9
'操作后库存 10
'操作金额 11
'销售利润 12
'历史总利润 13
'客户人次 14
'库存总价值 15
'进货价 16
'销售价 17
'单位毛利 18
'毛利率 19
'销售次数 20
'生产日期 21
'保质期 22
'过期 23




